# Generated by Django 5.0 on 2025-02-14 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.CharField(max_length=100, verbose_name='Codigo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Banco',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Forma de pagamento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StatusMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Categoria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovementFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('value_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Pagamento')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('file', models.TextField(verbose_name='Arquivo')),
                ('is_installment', models.BooleanField(default=False, verbose_name='Parcelamento')),
                ('installment', models.IntegerField(verbose_name='Parcela')),
                ('related_id', models.IntegerField(verbose_name='Movimentações Relacionadas')),
                ('payment_at', models.DateField(verbose_name='Data de Pagamento')),
                ('due_at', models.DateField(verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.bank', verbose_name='Banco')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.category', verbose_name='Categoria')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.statusmovement', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Movimentações',
                'ordering': ['due_at'],
            },
        ),
        migrations.AddField(
            model_name='statusmovement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='finance.typemovement', verbose_name='Tipo de Movimentação'),
        ),
        migrations.AddField(
            model_name='category',
            name='type_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorys', to='finance.typemovement', verbose_name='Tipo de Movimentação'),
        ),
    ]
