# Generated by Django 5.0 on 2025-02-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typemovement',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Movimentação'},
        ),
        migrations.AlterField(
            model_name='movementfinancial',
            name='file',
            field=models.TextField(blank=True, null=True, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='movementfinancial',
            name='installment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='movementfinancial',
            name='payment_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='movementfinancial',
            name='related_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimentações Relacionadas'),
        ),
    ]
